### ISSUE TITLE
Trending Module needs improvement

### ISSUE THREAD

**Issue by adityabhimesha** [adityabhimesha/safe-trip-backend#1]
For now the trending only sends over the last 10 most popular tokens, it would be better if we can get the 10 most transacted pair from bitquery dextrades API and send em over. keeping it real time and active trending, instead of just visit counter.

**Comment by 0xWWW** [comment]
bitquery dex trades api url is `https://graphql.bitquery.io/ide/7wwCJHGiC6#`, correct?
